# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:title

exclude: ["markdown_styleguide.md", ".rvmrc", "jekyll.gems", ".rbenv-version", "README.md", "Rakefile", "CNAME"]
auto: true
pygments: true

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Kiji Community
author :
  name : WibiData
  email : admin@wibidata.com
  github : kijiproject
  twitter : kijiproject

# URL of the kiji site.
#
kiji_url : http://www.kiji.org

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://docs.kiji.org
api_url : /apidocs
userguide_url : /userguides
tutorial_url : /tutorials

# rc1
api_schema_rc1 : http://api-docs.kiji.org/kiji-schema/1.0.0-rc1/org/kiji/schema
userguide_schema_rc1 : /userguides/schema/1.0.0-rc1

# rc2
api_schema_rc2 : http://api-docs.kiji.org/kiji-schema/1.0.0-rc2/org/kiji/schema
userguide_schema_rc2 : /userguides/schema/1.0.0-rc2

# rc3
api_schema_rc3 : http://api-docs.kiji.org/kiji-schema/1.0.0-rc3/org/kiji/schema
tutorial_phonebook_rc3 : /tutorials/phonebook-tutorial/1.0.0-rc3
userguide_schema_rc3 : /userguides/schema/1.0.0-rc3

# rc4
api_schema_rc4 : http://api-docs.kiji.org/kiji-schema/1.0.0-rc4/org/kiji/schema
api_mr_rc4 : http://api-docs.kiji.org/kiji-mapreduce/1.0.0-rc4/org/kiji/mapreduce
api_mrlib_rc4 : http://api-docs.kiji.org/kiji-mapreduce-lib/1.0.0-rc4/org/kiji/mapreduce
tutorial_phonebook_rc4 : /tutorials/phonebook-tutorial/1.0.0-rc4
tutorial_music_rc4 : /tutorials/music-recommendation/1.0.0-rc4
userguide_schema_rc4 : /userguides/schema/1.0.0-rc4
userguide_mapreduce_rc4 : /userguides/mapreduce/1.0.0-rc4

# rc5
api_schema_rc5 : http://api-docs.kiji.org/kiji-schema/1.0.0-rc5/org/kiji/schema
api_mr_rc5 : http://api-docs.kiji.org/kiji-mapreduce/1.0.0-rc5/org/kiji/mapreduce
api_mrlib_rc5 : http://api-docs.kiji.org/kiji-mapreduce-lib/1.0.0-rc5/org/kiji/mapreduce
tutorial_phonebook_rc5 : /tutorials/phonebook-tutorial/1.0.0-rc5
tutorial_music_rc5 : /tutorials/music-recommendation/1.0.0-rc5
userguide_schema_rc5 : /userguides/schema/1.0.0-rc5
userguide_mapreduce_rc5 : /userguides/mapreduce/1.0.0-rc5

# Express
api_express_0_1_0 : http://api-docs.kiji.org/kiji-express/0.1.0/org/kiji/express

# BentoBox Albacore
api_schema_1_0_0 : http://api-docs.kiji.org/kiji-schema/1.0.0/org/kiji/schema
api_schema_1_0_1 : http://api-docs.kiji.org/kiji-schema/1.0.1/org/kiji/schema
api_schema_1_0_2 : http://api-docs.kiji.org/kiji-schema/1.0.2/org/kiji/schema
api_mr_rc6 : http://api-docs.kiji.org/kiji-mapreduce/1.0.0-rc6/org/kiji/mapreduce
api_mr_rc61 : http://api-docs.kiji.org/kiji-mapreduce/1.0.0-rc61/org/kiji/mapreduce
api_mrlib_rc6 : http://api-docs.kiji.org/kiji-mapreduce-lib/1.0.0-rc6/org/kiji/mapreduce
api_mrlib_rc61 : http://api-docs.kiji.org/kiji-mapreduce-lib/1.0.0-rc61/org/kiji/mapreduce
tutorial_phonebook_rc6 : /tutorials/phonebook-tutorial/1.0.0-rc6
tutorial_music_rc6 : /tutorials/music-recommendation/1.0.0-rc6
userguide_schema_1_0_0 : /userguides/schema/1.0.0
userguide_schema_1_0_1 : /userguides/schema/1.0.1
userguide_schema_1_0_2 : /userguides/schema/1.0.2
userguide_mapreduce_rc6 : /userguides/mapreduce/1.0.0-rc6
userguide_mapreduce_rc61 : /userguides/mapreduce/1.0.0-rc61

# Latest development versions of project documentation.
# When these documents are released, they are copied to a directory named
# after the release version number and have their DEVEL macros finalized to the
# latest release versions.

api_schema_DEVEL : http://api-docs.kiji.org/kiji-schema/devel/org/kiji/schema
api_mrlib_DEVEL : http://api-docs.kiji.org/kiji-mapreduce-lib/devel/org/kiji/mapreduce
api_mr_DEVEL : http://api-docs.kiji.org/kiji-mapreduce/devel/org/kiji/mapreduce
api_express_DEVEL : http://api-docs.kiji.org/kiji-express/devel/org/kiji/express

userguide_schema_devel : /userguides/schema/devel
userguide_mapreduce_devel : /userguides/mapreduce/devel
userguide_express_devel : /userguides/express/devel
userguide_rest_devel : /userguides/rest/devel

tutorial_phonebook_devel : /tutorials/phonebook-tutorial/devel
tutorial_music_devel : /tutorials/music-recommendation/devel
tutorial_express_devel : /tutorials/express-recommendation/devel

schema_devel_version : 1.2.2
schema_devel_branch : master

mr_devel_version : 1.1.1
mr_devel_branch : master

mrlib_devel_version : 1.0.1
mrlib_devel_branch : master

express_devel_version : 0.9.0
express_devel_branch : master

phonebook_devel_version : 1.0.1

music_devel_version : 1.0.1
music_devel_branch : master

music_express_devel_version : 0.8.0
music_express_devel_branch : master

rest_devel_version: 0.5.0
rest_devel_branch : master

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.2.13

  # All links will be namespaced by BASE_PATH if defined.
  # Links in your website should always be prefixed with {{BASE_PATH}}
  # however this value will be dynamically changed depending on your deployment situation.
  #
  # CNAME (http://yourcustomdomain.com)
  #   DO NOT SET BASE_PATH
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Pages (http://username.github.com)
  #   DO NOT SET BASE_PATH
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Project Pages (http://username.github.com/project-name)
  #
  #   A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
  #  REQUIRED! Set BASE_PATH to: http://username.github.com/project-name
  #
  # CAUTION:
  #   - When in Localhost, your site will run from root "/" regardless of BASE_PATH
  #   - Only the following values are falsy: ["", null, false]
  #   - When setting BASE_PATH it must be a valid url.
  #     This means always setting the protocol (http|https) or prefixing with "/"
  BASE_PATH : false

  # By default, the asset_path is automatically defined relative to BASE_PATH plus the enabled theme.
  # ex: [BASE_PATH]/assets/themes/[THEME-NAME]
  #
  # Override this by defining an absolute path to assets here.
  # ex:
  #   http://s3.amazonaws.com/yoursite/themes/watermelon
  #   /assets
  #
  ASSET_PATH : false

  # These paths are to the main pages Jekyll-Bootstrap ships with.
  # Some JB helpers refer to these paths; change theme here if needed.
  #
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html

  # Settings for comments helper
  # Set 'provider' to the comment provider you want to use.
  # Set 'provider' to false to turn commenting off globally.
  #
  #comments :
  #  provider : disqus
  #  disqus :
  #    short_name : jekyllbootstrap
  #  livefyre :
  #    site_id : 123
  #  intensedebate :
  #    account : 123abc
  #  facebook :
  #    appid : 123
  #    num_posts: 5
  #    width: 580
  #    colorscheme: light

  # Settings for analytics helper
  # Set 'provider' to the analytics provider you want to use.
  # Set 'provider' to false to turn analytics off globally.
  #
  analytics :
    provider : google
    google :
        tracking_id : 'UA-35866189-1'

  # Settings for sharing helper.
  # Sharing is for things like tweet, plusone, like, reddit buttons etc.
  # Set 'provider' to the sharing provider you want to use.
  # Set 'provider' to false to turn sharing off globally.
  #
  sharing :
    provider : false

  # Settings for all other include helpers can be defined by creating
  # a hash with key named for the given helper. ex:
  #
  #   pages_list :
  #     provider : "custom"
  #
  # Setting any helper's provider to 'custom' will bypass the helper code
  # and include your custom code. Your custom file must be defined at:
  #   ./_includes/custom/[HELPER]
  # where [HELPER] is the name of the helper you are overriding.

userguide_schema_1_0_3 : /userguides/schema/1.0.3
api_schema_1_0_3 : http://api-docs.kiji.org/kiji-schema/1.0.3/org/kiji/schema
api_mr_1_0_0_rc62 : http://api-docs.kiji.org/kiji-mapreduce/1.0.0-rc62/org/kiji/mapreduce
userguide_mapreduce_1_0_0_rc62 : /userguides/mapreduce/1.0.0-rc62
api_mrlib_1_0_0_rc61 : http://api-docs.kiji.org/kiji-mapreduce-lib/1.0.0-rc61/org/kiji/mapreduce
api_express_0_2_0 : http://api-docs.kiji.org/kiji-express/0.2.0/org/kiji/express
api_express_0_3_0 : http://api-docs.kiji.org/kiji-express/0.3.0/org/kiji/express
userguide_schema_1_0_4 : /userguides/schema/1.0.4
api_schema_1_0_4 : http://api-docs.kiji.org/kiji-schema/1.0.4/org/kiji/schema
api_express_0_4_0 : http://api-docs.kiji.org/kiji-express/0.4.0/org/kiji/express
userguide_schema_1_1_0 : /userguides/schema/1.1.0
api_schema_1_1_0 : http://api-docs.kiji.org/kiji-schema/1.1.0/org/kiji/schema
api_mr_1_0_0 : http://api-docs.kiji.org/kiji-mapreduce/1.0.0/org/kiji/mapreduce
userguide_mapreduce_1_0_0 : /userguides/mapreduce/1.0.0
tutorial_phonebook_1_0_0 : /tutorials/phonebook-tutorial/1.0.0
api_mrlib_1_0_0 : http://api-docs.kiji.org/kiji-mapreduce-lib/1.0.0/org/kiji/mapreduce
api_express_0_5_0 : http://api-docs.kiji.org/kiji-express/0.5.0/org/kiji/express
userguide_schema_1_1_1 : /userguides/schema/1.1.1
api_schema_1_1_1 : http://api-docs.kiji.org/kiji-schema/1.1.1/org/kiji/schema
api_mr_1_0_1 : http://api-docs.kiji.org/kiji-mapreduce/1.0.1/org/kiji/mapreduce
userguide_mapreduce_1_0_1 : /userguides/mapreduce/1.0.1
api_express_0_6_0 : http://api-docs.kiji.org/kiji-express/0.6.0/org/kiji/express
userguide_rest_0_3_0 : /userguides/rest/0.3.0
userguide_schema_1_1_2 : /userguides/schema/1.1.2
api_schema_1_1_2 : http://api-docs.kiji.org/kiji-schema/1.1.2/org/kiji/schema
api_mr_1_0_2 : http://api-docs.kiji.org/kiji-mapreduce/1.0.2/org/kiji/mapreduce
userguide_mapreduce_1_0_2 : /userguides/mapreduce/1.0.2
userguide_schema_1_2_0 : /userguides/schema/1.2.0
api_schema_1_2_0 : http://api-docs.kiji.org/kiji-schema/1.2.0/org/kiji/schema
api_mr_1_1_0 : http://api-docs.kiji.org/kiji-mapreduce/1.1.0/org/kiji/mapreduce
userguide_mapreduce_1_1_0 : /userguides/mapreduce/1.1.0
api_express_0_7_0 : http://api-docs.kiji.org/kiji-express/0.7.0/org/kiji/express

userguide_schema_1_2_1 : /userguides/schema/1.2.1
api_schema_1_2_1 : http://api-docs.kiji.org/kiji-schema/1.2.1/org/kiji/schema
api_express_0_8_0 : http://api-docs.kiji.org/kiji-express/0.8.0/org/kiji/express
